### ISSUE TITLE
new site

### ISSUE THREAD

**Issue by jpeg115** [xHossein/PyPasser#2]
Wasn't sure where to ask. Could you add hbomax.com as a new site?

https://www.google.com/recaptcha/enterprise/anchor?ar=1&k=6LeMrv8ZAAAAAIcvo5HKvdj1lxtUdHnS13jUCulQ&co=aHR0cHM6Ly9wbGF5Lmhib21heC5jb206NDQz&hl=en&v=wxAi4AKLXL2kBAvXqI4XLSWS&size=invisible&cb=4dxv36bwkio3

**Comment by xHossein** [comment]
The next update will include this site.

But you can bypass it by [CustomSite ](https://github.com/xHossein/PyPasser#option-2-use-customsite-for-unadded-sites) too:
```python
from pypasser import reCaptchaBypasser
from pypasser.structs import CustomSite

config = CustomSite('PUT ANCHOR URL HERE')
reCaptcha_response = reCaptchaBypasser(config)
```

**Comment by jpeg115** [comment]
Have tried without success....keep getting message 
Request failed the recaptcha test

**Comment by jpeg115** [comment]
I may not be doing it correctly....still relatively new to Python. At one point, I also got the same error as 
the other person did...

TypeError: __init__() takes 2 positional arguments but 3 were given

The HBOMAX site seems to be intertwined with multiple recaptcha requests, so the attempts
for me may have been doomed from the start.

**Comment by xHossein** [comment]
That type-error is because of passing 2 things to `CustomSite`.
Just pass anchor_url to CustomSite, not anything else. (it's in the doc)

I tested by the anchor url you sent before and PyPasser got the recaptcha response (rresp) successfully.

But maybe this generated rresp is not valid on that site (e.g. in login req). you should test and figure out by yourself.

**Comment by jpeg115** [comment]
Thanks for testing and letting me know. I figured I was doing something wrong and I do need to figure it out myself.
